services:
  _defaults:
    autowire: true
    autoconfigure: true

#  _instanceof:
#    Machine\LegacyBridgeBundle\Factory\LegacyRouteGeneratorInterface:
#      tags: [ 'machine.legacy_route_generator' ]

#  Machine\LegacyBridgeBundle\Factory\LegacyRouteFactory:
#    public: true
#    arguments:
#      - !tagged_iterator machine.legacy_route_generator

#  Machine\LegacyBridgeBundle\Factory\LegacyRouteGeneratorInterface: '@Machine\LegacyBridgeBundle\Factory\LegacyRouteFactory'

  machine_legacy_bridge.routing_loader:
    class: Machine\LegacyBridgeBundle\Routing\LegacyRouteLoader
    arguments:
      $legacyPath: '%machine_legacy_bridge.legacy_path%'
    tags: ['routing.loader']
    public: true

  machine_legacy_bridge.legacy_controller:
    class: Machine\LegacyBridgeBundle\Controller\LegacyScriptController
    calls:
      - setContainer: ['@service_container']
      - setPrependScript: ['%machine_legacy_bridge.prepend_script%']
      - setAppendScript: ['%machine_legacy_bridge.append_script%']
